name: deploy chatGPT server to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      ENV_FILE_PATH: ${{ secrets.ENV_FILE_PATH }}
    steps:
      - name: ssh로 서버 접근 & git pull 후 재배포 진행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            touch ${{ env.ENV_FILE_PATH }}
            echo "${{ secrets.ENV }}" > ${{ env.ENV_FILE_PATH }}
            source ${{ env.ENV_FILE_PATH }}
            echo OPEN_AI_KEY
            cd /home/ubuntu/spring-chatgpt-communication
            git pull origin main
            ./gradlew clean build
            sudo fuser -k -n tcp ${{ env.SERVER_PORT }} || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &